### ISSUE TITLE
“语(jyu5)”字yy打不出来的解决办法

### ISSUE THREAD

**Issue by nickqoop** [MrCorn0-0/jyutsp#1]
jyutsp.schema.yaml文件：
\- xform/^jyu$/YU/
改为
\- xform/^jyu$/YY/

**Comment by MrCorn0-0** [comment]
雖然這是一個年久失修的方案，但非常感謝關注並提出issue。
但本方案設計之初就是 jyu音用 y+u打出：
> [關於jyu韻，本方案處理為 yu。](https://github.com/MrCorn0-0/jyutsp?tab=readme-ov-file#%E9%9F%BB%E6%AF%8D)

你可以在你的本地佈署時更改成你習慣的輸入方式。

**Comment by nickqoop** [comment]
谢谢回复和分享。但是根据提供的码表jyu是yy。
我改造一下，适合自己用，也方便自己掌握粤语输入。
rime和git我都是新手。
我关掉issue了。
和微软双拼一致，改为o键作为零声母。用了才会发现哪些地方改了会更顺手。
文件如下：

jyutsp.schema.yaml

```yaml
# Rime schema
# encoding: utf-8

schema:
  schema_id: jyutsp
  name: 粤语双拼
  version: "1.0"
  author:
    - nickqoop

  description:
    jyutsp - https://github.com/MrCorn0-0/jyutsp

switches:
  - name: ascii_mode
    states: [ 中文, En ]
  - name: full_shape
    states: [ 半角, 全角 ]
  - name: simplification
    states: [ 繁, 简 ]
  - name: ascii_punct
    states: [ 。, . ]

engine:
  processors:
    - ascii_composer
    - recognizer
    - key_binder
    - speller
    - punctuator
    - selector
    - navigator
    - express_editor
  segmentors:
    - ascii_segmentor
    - matcher
    - abc_segmentor
    - punct_segmentor
    - fallback_segmentor
  translators:
    - punct_translator
    - script_translator
  filters:
    - simplifier
    - uniquifier

speller:
  alphabet: zyxwvutsrqponmlkjihgfedcba;
  algebra:
    - xform/([123456])//
    - derive/^ng$/m/
    - xform/^([aeiou])/O$1/
    - xform/yun$/R/
    - xform/yut$/D;/
    - xform/^gu$/GU/
    - xform/yu/Y/
    - xform/^j/Y/
    - derive/^s(?!i)/U$1/
    - derive/^si$/UI/
    - derive/^c(.+)/I$1/
    - derive/^z(.+)/J$1/
    - xform/^kw/Q/
    - xform/^gw/X/
    - xform/^ku([itk]?)$/Qu$1/
    - derive/^Qu$/KU/
    - xform/^gu([ink]?)$/Xu$1/
    - xform/^ng/R/
    - xform/iu$/Q/
    - xform/eu$/Q/
    - xform/un$/R/
    - xform/oeng$/T/
    - xform/ut$/T/
    - xform/ou$/U/
    - xform/eot/O;/
    - xform/oet/O;/
    - xform/ong$/W/
    - xform/ot/W;/
    - xform/it/I;/
    - xform/et/I;/
    - xform/ok$/P/
    - xform/eon/P;/
    - xform/ung$/S/
    - xform/uk$/D/
    - xform/aap/V;/
    - xform/aai/V/
    - xform/aam$/H/
    - xform/aak/H;/
    - xform/ak/Q;/
    - xform/aang$/J;/
    - xform/aan$/J/
    - xform/aau/N;/
    - xform/ang/G;/
    - xform/an$/F/
    - xform/am$/G/
    - xform/ai$/L/
    - xform/aat/C;/
    - xform/at$/C/
    - xform/au$/B/
    - xform/ap/M;/
    - xform/aa$/A/
    - xform/a$/A;/
    - xform/ik$/K/
    - xform/oek/K;/
    - xform/ek/K;/
    - xform/ing$/;/
    - xform/eng/;;/
    - xform/ei$/Z/
    - xform/ip/Z;/
    - xform/ep/Z;/
    - xform/eoi$/X/
    - xform/ui$/X/
    - xform/(oe|eo)/T/
    - xform/in$/N/
    - xform/en$/N/
    - xform/im$/M/
    - xform/em$/M/
    - xform/oi/Y;/
    - xform/on$/E/
    - xform/(.*)ng$/$1R/
    - xlit/ABCDEFGHIJKLMNOPQRSTUVWXYZ/abcdefghijklmnopqrstuvwxyz/
    - derive/^k([s])/q$1/
    - derive/^g([s])/x$1/
    - derive/^e([aov])$/$1/
    - derive/^([a-z|;]{2});/$1/
    - xform/^(m|r)$/$1$1/
    - abbrev/^([a-z|;]{3}).+$/$1/

translator:
  dictionary: jyut6ping3
  prism: jyutsp

key_binder:
  import_preset: default

punctuator:
  import_preset: symbol
```

symbol.yaml

```yaml
# Rime symbol
# encoding: utf-8

punctuator:
  half_shape:
    "`": "·"
    "~": "～"
    "!": "！"
    "@": "@"
    "#": "#"
    "$": "¥"
    "%": "%"
    "^": "……"
    "&": "&"
    "*": "*"
    "(": "（"
    ")": "）"
    _: "——"
    "+": "+"
    "-": "-"
    "=": "="
    "[": "【"
    "]": "】"
    "{": "「"
    "}": "」"
    "\\": "、"
    "|": "|"
    ";": "；"
    ":": "："
    "'": {pair: ["‘", "’"]}
    "\"": {pair: ["“", "”"]}
    ",": "，"
    .: "。"
    "/": "/"
    "<": "《"
    ">": "》"
    "?": "？"
```
