### ISSUE TITLE
关于粤语双拼的启发

### ISSUE THREAD

**Issue by nickqoop** [MrCorn0-0/jyutsp#2]
#1 完善一下

根据微软双拼的实现，重新实现了一次粤语双拼，并测试没什么问题了，发一发，看看能不能实现其他方言的双拼方案。

**制作步骤**

1. 先找到 `.dict.yaml` 字典
2. 确定声母
3. 通过dict字典和声母，找出剩余的部分，排序去重，确定为复合韵母
4. 用声母和复合韵母，根据习惯，确定键盘码表
5. 编写 `.schema` 配置文件，[双拼方案](https://github.com/rime/rime-double-pinyin)
6. 修改 `.schema` 配置文件，按键盘排列字母配置，先声母后复合韵母，先多个字母的声母，如果复合韵母不能用移至其后
7. 测试，完成

**码表**

o是零声母

![Image](https://github.com/user-attachments/assets/4d7d245d-92e4-46d7-9154-96d84ffff3ff)

**rime安装**

[粵語拼音](https://jyutping.net/#other)

**schema文件**

```yaml
# Rime schema
# encoding: utf-8

schema:
  schema_id: test
  name: 测试
  version: "1.0"
  author:
    - nickqoop
  description:
    - https://github.com/MrCorn0-0/jyutsp
  dependencies:
    - jyut6ping3

switches:
  - name: ascii_mode
    reset: 0
    states: [ "测试", "En" ]
  - name: ascii_punct
    reset: 0
    states: [ "。", "." ]
  - name: full_shape
    reset: 0
    states: [ "半角", "全角" ]
  - name: simplification
#    reset: 0
    reset: 1
    states: [ "繁", "简" ]

engine:
  processors:
    - ascii_composer
    - recognizer
    - key_binder
    - speller
    - punctuator
    - selector
    - navigator
    - express_editor
  segmentors:
    - ascii_segmentor
    - matcher
    - abc_segmentor
    - punct_segmentor
    - fallback_segmentor
  translators:
    - punct_translator
    - script_translator
  filters:
    - simplifier
    - uniquifier

speller:
  alphabet: "abcdefghijklmnopqrstuvwxyz;"
  algebra:
    - xform/([1-6])//
    - xform/^([aeiou])/O$1/
    - xform/aa[mk]/H/
    - xform/uk|yut/D/
    - xform/[ie]k|oek/K/
    - xform/oe(ng)?|ut/T/
    - xform/ok|eon/P/
    - xform/aa[ip]/V/
    - xform/[ie]ng/;/
    - xform/aang?/J/
    - xform/in|aau/N/
    - xform/ung/S/
    - xform/am|ang/G/
    - xform/an/F/
    - xform/^kw/Q/
    - xform/^ng/R/
    - xform/^gw/X/
    - xform/eoi|ui/X/
    - xform/a?at/C/
    - xform/ap|[ei]m/M/
    - xform/eot|o?et$/O/
    - xform/ai/L/
    - xform/ak|[ei]u/Q/
    - xform/ong|ot/W/
    - xform/on/E/
    - xform/au/B/
    - xform/y?un/R/
    - xform/^t/T/
    - xform/^j/Y/
    - xform/yu|oi/Y/
    - xform/o?u/U/
    - xform/i?t|et/I/
    - xform/a?a/A/
    - xform/^s/S/
    - xform/ei|[ie]p/Z/
    - xlit/ABCDEFGHIJKLMNOPQRSTUVWXYZ/abcdefghijklmnopqrstuvwxyz/
    - xform/^([mr])$/$1$1/

translator:
  dictionary: jyut6ping3
  prism: test

punctuator:
  import_preset: symbol

key_binder:
  import_preset: default
```

[粤语拼音查询](https://www.iamwawa.cn/yuepin.html)

**示例**

這是一個示例。/zesiycgosill

![Image](https://github.com/user-attachments/assets/a7dee9fd-fa82-4d4d-8495-a0bb21c60253)
